name: Deploy Website to EKS

on:
  push:
    branches:
      - feature/demo-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 905418383753.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Docker Image to ECR
        run: |
          IMAGE_TAG=$(date +%s)
          ECR_REPO_URI=905418383753.dkr.ecr.ap-south-1.amazonaws.com/demo-website
          docker build -t $ECR_REPO_URI:$IMAGE_TAG ./my-website
          docker push $ECR_REPO_URI:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "ECR_REPO_URI=$ECR_REPO_URI" >> $GITHUB_ENV

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster

      - name: Update deployment image and apply
        run: |
          sed -i "s|image:.*|image: $ECR_REPO_URI:$IMAGE_TAG|" deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
